import { jsPDF } from 'jspdf';

export interface PdfExportParams {
  task: string;
  appName?: string;
  model?: string;
  result: string | Record<string, unknown>;
  processingMs?: number;
}

export function downloadPdf(params: PdfExportParams): void {
  const doc = new jsPDF();
  const margin = 16;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxLineWidth = pageWidth - margin * 2;

  const title = `APAP AI — ${params.task.replace(/-/g, ' ').toUpperCase()}`;
  doc.setFontSize(16);
  doc.text(title, pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Generated by: ${params.appName || 'APAP AI Gateway'}`, margin, 30);
  doc.text(`Model: ${params.model || 'Unknown'}`, margin, 36);
  if (params.processingMs) {
    doc.text(`Processing time: ${params.processingMs} ms`, margin, 42);
  }
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 48);

  const content =
    typeof params.result === 'string'
      ? params.result
      : JSON.stringify(params.result, null, 2);

  const lines = doc.splitTextToSize(content, maxLineWidth);
  doc.setFontSize(11);
  doc.setTextColor(20, 20, 20);
  doc.text(lines, margin, 60);

  const safeTask = params.task.replace(/[^a-z0-9-]/gi, '-');
  const date = new Date().toISOString().slice(0, 10);
  doc.save(`apap-ai-${safeTask}-${date}.pdf`);
}
